# Rust project
language: rust
cache: cargo

rust:
- 1.13.0
- stable
- beta
- nightly
matrix:
  allow-failures:
  - rust: nightly

before-script:
- which cargo-todox || cargo-install cargo-todox # ALLOW TODOX

# Build & Test
script:
- cargo todox # ALLOW TODOX
- cargo build --verbose
- cargo test --verbose
